xxtname: reposheet-environment
channels:
  - conda-forge
dependencies:
  - appmode
  - jupyterlab==4.0.7
  - pip
  - pip:
    - memoization
  - PyGithub
  - python-gitlab
  - python==3.11.6
  - qgrid
  - tqdm
  - voila
